version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: codeforge_sql
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    build: ./CodeForge__BE
    container_name: codeforge_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__Default=Server=${DB_HOST},${DB_PORT};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;
    ports:
      - "5000:8080" # đổi 80 thành 8080
    depends_on:
      - db

  frontend:
    build: ./CodeForge__FE
    container_name: codeforge_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  sql_data:
